//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace classManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Receipts
    {
        public int ID { get; set; }
        public string Customer_name { get; set; }
        public string Service { get; set; }
        public decimal Receipt_Amount { get; set; }
        public decimal Balance { get; set; }
    }
}
